language: node_js
node_js:
- '7'
before_script:
- yarn
script:
- yarn run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_437c132ca673_key -iv $encrypted_437c132ca673_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR && git add dist && git commit -m "Deploy $TRAVIS_COMMIT ($TRAVIS_BUILD_ID)" && git push origin master && git subtree push --prefix dist origin gh-pages
