language: node_js

node_js:
  - '8'

services:
  - docker

before_script:
  - yarn

script:
  - yarn run generate
  - docker build . --tag dianw/crema:latest
  - PUBLIC_PATH=https://crema.enkrip.org yarn run generate

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dianw/crema;
    fi

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  fqdn: crema.enkrip.org
  github_token:
    secure: "sR5WmGFgOeicHx6Uwf8Cr8LZi7VOHzawDdBAo8zR11wIZ9QiuMKu6Re7XTcxSfdpordsgm5Rd7CzyfjmwsLiKI3SReQm3I/CJq4f7/VoUskuL9Z0DCW1/NEBIIGa7Z5Or1K5XTNWjW8c5g/+ZNz0RfklzOOlmD65ejkNSTDQpRb2MC9gfqm9ySEu9VL8Wv6Xn69psyn07/+YyGqBShjx5BTQWYkLlEmla5NaPJWmI3U5duwtcK+tudsc7jXKC6bec7dF70gu9YQZ4evhhlcU+WXZuAphJpcV7P4QlHVXLB63OOlIC3L1+nt2001155fjuuYltm/FnHA3GqfC3Zvbfan2vAlDTEUbz5gidoZ1IYgmDEUcWR3BnTmpgVLwrd0Ba1H01Xaavt8Q8FLaD5FhjaEfALRptQP7qk4bFM/ejnUO3r3Zrm+fYKZY45mJbJ75gGcN0CSxKRgLBQ9hd2nPY+udDO1J469o+Y2wYdj/LTso2VwrV8FuUo7XYaUNBnkAZrH1UHuxjg2shx4yj9ifIYrmO8lhnUSqTSIyq13M01Qzp1TZnTVbdC14YKt8dVke1Q3qI/F4EOlI5J81pkBIqTG0KrYNC8w5hyFs963y32Go0ABoujDFRJDuiXqz66OmJiGznWIWBDxYj1mcux39BHnlSu9leK9Nhq1UlK2TdRg="
  on:
    branch: master
