# GitHub Actions workflow to replace Travis CI for crema
# This workflow builds, tests, builds Docker image, pushes to Docker Hub, and deploys to GitHub Pages

name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn
      - name: Generate static site
        run: yarn run generate
      - name: Build Docker image
        run: docker build . --tag dianw/crema:latest
      - name: Generate static site with PUBLIC_PATH
        run: PUBLIC_PATH=https://crema.enkrip.org yarn run generate
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: docker push dianw/crema:latest
      - name: Upload artifact for GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4
        with:
          cname: crema.enkrip.org
